"""Repeated-structure detection (T2-05): find the list without knowing the selector.

Tier 1 works because someone wrote a selector for each of five known sites. Tier 2 cannot:
there are ~1,200 unknown templates and nobody is writing a thousand selectors. What every
one of those pages *does* have is repetition — a course list, a price table, a schedule is
a block whose structure repeats once per record.

So this module finds records by shape rather than by name. It groups sibling elements by a
normalized structural signature, and scores each group on whether it looks like data.

The hard part is not finding repetition. It is that **navigation menus, pagination, tag
clouds, social icons and cookie banners all repeat too**, and they repeat more regularly
than real data does. A detector that only counts repeats returns the nav bar on every site
on the internet. The scoring here is mostly about telling data from furniture:

* Records carry text; nav items carry a word or two.
* Records vary in length; nav items are uniform.
* Records contain the fields we came for — a price, a date, a course keyword, a phone.
* Furniture lives inside ``nav``/``header``/``footer``, or is a run of bare links.

Never raises, bounded, deterministic.
"""
from __future__ import annotations

import re
import statistics
import unicodedata
from dataclasses import dataclass, field
from typing import Iterable, Optional, Sequence

MAX_NODES = 20_000
MAX_CANDIDATES = 400
MIN_ROWS = 3
MAX_ROWS = 2_000

#: Classes generated by build tools carry a content hash that differs per deploy and often
#: per element. Treating them as identity makes every row look structurally unique.
_HASHED_CLASS = re.compile(r"^(?:css|sc|jsx|emotion|styles?)[-_]?[0-9a-z]{5,}$", re.I)
_TRAILING_INDEX = re.compile(r"[-_]?\d+$")
_STATE_CLASS = re.compile(
    r"^(?:is|has|js)[-_]|^(?:active|selected|current|first|last|odd|even|hover|open"
    r"|visible|hidden|col|row)[-_]?\d*$",
    re.I,
)

FURNITURE_TAGS = frozenset({"nav", "header", "footer", "aside", "form", "script",
                            "style", "noscript", "svg", "select", "template"})
FURNITURE_HINTS = (
    "nav", "menu", "breadcrumb", "pagination", "pager", "social", "share", "cookie",
    "banner", "footer", "header", "sidebar", "widget", "tag-cloud", "skip", "toolbar",
    "language", "lang-switch", "search",
)

_PRICE_SHAPED = re.compile(
    r"(?:[€£$¥]|\b(?:EUR|GBP|USD|SEK|NOK|DKK|PLN|CZK|CHF)\b)\s*\d"
    r"|\d[\d   .,]*\s*(?:[€£$]|\b(?:EUR|GBP|USD|SEK|NOK|DKK|PLN|CZK|CHF)\b)",
    re.IGNORECASE,
)
_DATE_SHAPED = re.compile(
    r"\b\d{1,2}[./-]\d{1,2}[./-]\d{2,4}\b|\b\d{4}-\d{2}-\d{2}\b"
    r"|\b\d{1,2}\s+(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)", re.IGNORECASE
)
_DURATION_SHAPED = re.compile(
    r"\b\d{1,3}\s*(?:days?|hours?|hrs?|weeks?|dienas|stundas|paeva|tage|dagar|dni)\b",
    re.IGNORECASE,
)
_COURSE_WORDS = re.compile(
    r"\b(?:gwo|opito|irata|bosiet|foet|huet|bst|bstr|vts|nebosh|iosh|level\s*[123]"
    r"|course|training|kurs\w*|koolitus\w*|szkolen\w*|certificat\w*|refresher)\b",
    re.IGNORECASE,
)
_PHONE_SHAPED = re.compile(r"(?:\+|00)\d[\d\s\-().]{6,}\d")


@dataclass
class Region:
    """One repeating block of records found on a page."""

    signature: str
    container_locator: str
    row_locators: list[str]
    score: float
    evidence: list[str] = field(default_factory=list)
    rows: list = field(default_factory=list, repr=False)
    container: object = field(default=None, repr=False)

    @property
    def row_count(self) -> int:
        return len(self.row_locators)

    def as_dict(self) -> dict:
        return {"signature": self.signature, "container": self.container_locator,
                "row_count": self.row_count, "score": round(self.score, 2),
                "evidence": list(self.evidence),
                "rows": list(self.row_locators[:20])}


# -- signatures --------------------------------------------------------------------------


def _normalize_classes(value: Optional[str]) -> tuple[str, ...]:
    """Reduce a class attribute to the part that means "same kind of thing"."""
    if not value:
        return ()
    kept = []
    for token in value.split():
        token = token.strip().lower()
        if not token or _HASHED_CLASS.match(token) or _STATE_CLASS.match(token):
            continue
        token = _TRAILING_INDEX.sub("", token)
        if token:
            kept.append(token)
    return tuple(sorted(set(kept)))


def _child_shape(element, limit: int = 12) -> str:
    tags = []
    for child in list(element)[:limit]:
        tag = child.tag
        if isinstance(tag, str):
            tags.append(tag.lower())
    return ",".join(tags)


def signature_of(element) -> str:
    """A structural fingerprint: same signature means "same kind of record"."""
    tag = element.tag if isinstance(element.tag, str) else "?"
    classes = ".".join(_normalize_classes(element.get("class")))
    return f"{tag.lower()}|{classes}|{_child_shape(element)}"


def _locator(element, fallback: str = "?") -> str:
    try:
        return element.getroottree().getpath(element)
    except Exception:
        return fallback


def _text(element, limit: int = 4000) -> str:
    """Row text with cell boundaries preserved.

    ``text_content()`` concatenates without separators, turning
    "<td>Training</td><td>5 days</td>" into "Training5 days" — which merges a course name
    into a duration and corrupts every downstream parse and evidence quote.
    """
    try:
        parts = [" ".join(chunk.split()) for chunk in element.itertext()]
        return " ".join(part for part in parts if part)[:limit]
    except Exception:
        return ""


def row_cells(region: "Region") -> list[list[str]]:
    """Per-row cell text, so extraction can be column-aware.

    A price table states name, duration and price in separate cells. Reading columns keeps
    that association; running regexes over the flattened row throws it away and leaves the
    price unattached to any particular course.
    """
    cells: list[list[str]] = []
    for row in region.rows:
        try:
            children = [child for child in row
                        if isinstance(getattr(child, "tag", None), str)]
        except Exception:
            children = []
        if children:
            cells.append([_text(child, 500) for child in children])
        else:
            cells.append([_text(row, 500)])
    return cells


def column_profile(region: "Region") -> list[str]:
    """Guess what each column holds, from the values in it.

    Returns one label per column: ``price``, ``date``, ``duration``, ``course`` or
    ``text``. Columns of differing width fall back to ``text`` for the ragged part.
    """
    grid = row_cells(region)
    if not grid:
        return []
    width = max(len(row) for row in grid)
    labels: list[str] = []
    for index in range(width):
        values = [row[index] for row in grid if index < len(row) and row[index]]
        if not values:
            labels.append("text")
            continue
        for pattern, label in ((_PRICE_SHAPED, "price"), (_DURATION_SHAPED, "duration"),
                               (_DATE_SHAPED, "date"), (_COURSE_WORDS, "course")):
            if sum(1 for value in values if pattern.search(value)) >= max(
                    1, len(values) // 2):
                labels.append(label)
                break
        else:
            labels.append("text")
    return labels


def _fold(text: str) -> str:
    folded = unicodedata.normalize("NFKD", text or "")
    return "".join(ch for ch in folded if not unicodedata.combining(ch)).lower()


def _is_furniture(element) -> tuple[bool, str]:
    """Whether this element is page furniture rather than data."""
    node = element
    for _ in range(8):
        if node is None:
            break
        tag = node.tag if isinstance(node.tag, str) else ""
        if tag.lower() in FURNITURE_TAGS:
            return True, f"inside <{tag.lower()}>"
        attributes = _fold(f"{node.get('class') or ''} {node.get('id') or ''} "
                           f"{node.get('role') or ''}")
        for hint in FURNITURE_HINTS:
            if hint in attributes:
                return True, f"ancestor marked {hint!r}"
        node = node.getparent()
    return False, ""


# -- scoring -----------------------------------------------------------------------------


def _score_group(rows: Sequence, texts: Sequence[str]) -> tuple[float, list[str]]:
    """Score a candidate group on how much it looks like data rather than furniture."""
    evidence: list[str] = []
    count = len(rows)
    score = min(3.0, 0.6 * count)
    evidence.append(f"{count} sibling rows share a structure")

    lengths = [len(text) for text in texts]
    median_length = statistics.median(lengths) if lengths else 0
    if median_length < 12:
        score -= 3.0
        evidence.append(f"median row text is {median_length} chars — reads as navigation")
    elif median_length < 30:
        score -= 0.5
        evidence.append(f"short rows (median {median_length} chars)")
    else:
        score += 1.0
        evidence.append(f"rows carry text (median {median_length} chars)")

    # Real records vary in length; menu items are uniform. Zero variance across many rows
    # is the single clearest furniture tell.
    if count >= 4 and len(set(lengths)) == 1:
        score -= 1.5
        evidence.append("every row is exactly the same length — generated furniture")

    joined = " ".join(texts)
    for pattern, weight, label in (
        (_PRICE_SHAPED, 2.5, "prices"),
        (_COURSE_WORDS, 2.0, "course terms"),
        (_DATE_SHAPED, 1.0, "dates"),
        (_DURATION_SHAPED, 1.0, "durations"),
        (_PHONE_SHAPED, 1.0, "phone numbers"),
    ):
        hits = sum(1 for text in texts if pattern.search(text))
        if hits:
            share = hits / count
            score += weight * min(1.0, share * 1.5)
            evidence.append(f"{hits}/{count} rows contain {label}")

    # A run of rows that are nothing but one link each is a menu.
    bare_links = sum(1 for row, text in zip(rows, texts)
                     if _is_bare_link(row, text))
    if bare_links == count and count >= 3:
        score -= 2.5
        evidence.append("every row is a bare link")

    if count > MAX_ROWS:
        score -= 2.0
        evidence.append("implausibly many rows")
    return score, evidence


def _is_bare_link(row, text: str) -> bool:
    try:
        links = row.xpath(".//a")
    except Exception:
        return False
    if len(links) != 1:
        return False
    link_text = " ".join(links[0].text_content().split())
    return bool(link_text) and len(text) - len(link_text) <= 3


# -- detection ---------------------------------------------------------------------------


def find_repeated_regions(tree, *, min_rows: int = MIN_ROWS, max_regions: int = 5,
                          min_score: float = 2.0) -> list[Region]:
    """Find the repeating record blocks on a page, best first.

    Returns an empty list rather than raising when a page has no repetition, which is the
    correct answer for a single-course page.
    """
    if tree is None:
        return []
    try:
        elements = tree.iter()
    except Exception:
        return []

    candidates: list[Region] = []
    examined = 0
    for parent in elements:
        examined += 1
        if examined > MAX_NODES or len(candidates) >= MAX_CANDIDATES:
            break
        if not isinstance(getattr(parent, "tag", None), str):
            continue
        if parent.tag.lower() in FURNITURE_TAGS:
            continue

        children = [child for child in parent
                    if isinstance(getattr(child, "tag", None), str)
                    and child.tag.lower() not in FURNITURE_TAGS]
        if len(children) < min_rows:
            continue

        grouped: dict[str, list] = {}
        for child in children[:MAX_ROWS]:
            try:
                grouped.setdefault(signature_of(child), []).append(child)
            except Exception:
                continue

        for sig in sorted(grouped):
            rows = grouped[sig]
            if len(rows) < min_rows:
                continue
            furniture, why = _is_furniture(rows[0])
            texts = [_text(row) for row in rows]
            score, evidence = _score_group(rows, texts)
            if furniture:
                score -= 3.0
                evidence.append(f"furniture: {why}")
            if score < min_score:
                continue
            candidates.append(Region(
                signature=sig,
                container_locator=_locator(parent),
                row_locators=[_locator(row) for row in rows],
                score=score, evidence=evidence, rows=list(rows), container=parent,
            ))

    # Prefer the deepest, highest-scoring region: an outer container that merely wraps the
    # real list would otherwise win by containing it.
    candidates.sort(key=lambda region: (-region.score, -region.row_count,
                                        region.container_locator))
    chosen: list[Region] = []
    for region in candidates:
        if any(_contains(other.container_locator, region.container_locator)
               for other in chosen):
            continue
        chosen.append(region)
        if len(chosen) >= max_regions:
            break
    return chosen


def _contains(outer_locator: str, inner_locator: str) -> bool:
    return inner_locator.startswith(outer_locator + "/") or outer_locator == inner_locator


def best_region(tree, **kwargs) -> Optional[Region]:
    """The single most data-like repeating block, or None."""
    regions = find_repeated_regions(tree, **kwargs)
    return regions[0] if regions else None


def row_texts(region: Region) -> list[str]:
    """Plain text of each row, for feeding the field extractors."""
    return [_text(row) for row in region.rows]
